import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import Alerts from "../components/Alerts";
import Hotspots from "../components/Hotspots";
import Overview from "../components/Overview";
import MapPlaceholder from "../components/MapPlaceholder";
import Predictions from "../components/Predictions";
import Corridors from "../components/Corridors";
import Federation from "../components/Federation";
import GeminiPanel from "../components/GeminiPanel";
import CommandCenterPage from "../app/page";
import { api } from "../lib/api";
import type { Alert, Hotspot, ForecastResponse, PlumeResponse, ExposureResponse, CorridorPrediction, FederationStatusResponse, AgentChatResponse } from "../types/api";

jest.mock("../lib/api", () => ({ api: { getHotspots: jest.fn(), getAlerts: jest.fn(), updateAlertStatus: jest.fn(), getForecast: jest.fn(), getPlume: jest.fn(), getExposure: jest.fn(), getCorridorPredictions: jest.fn(), getFederationStatus: jest.fn(), chatWithAgent: jest.fn(), runDemo: jest.fn(), resetDemo: jest.fn() } }));

describe("VayuNet Command Center Comprehensive Contract Tests", () => {
  beforeEach(() => jest.clearAllMocks());
  const sampleHotspot: Hotspot = { hotspot_id: "h-123", latitude: 12.97, longitude: 77.59, score: 85.5, confidence: 0.92, severity: "HIGH", evidence_count: 5, source_types: ["industrial", "traffic"], pollutant_list: ["PM2.5"], anomaly_score: 8.5, spatial_score: 7, data_quality_score: 0.95, explanation: "Test hotspot explanation", city: "Bangalore", metadata: { source: "sensor" } };
  const baseAlert: Alert = { event_id: "evt-1", hotspot_id: "h-123", severity: "CRITICAL", priority_score: 95, priority_level: "P1", location: { lat: 12.97, lon: 77.59 }, likely_source: "Industrial", confidence: 0.98, affected_population: 5000, corridor: "East Corridor", predicted_peak: 180, assigned_authority: "PCB", status: "DETECTED", routing_reason: "High pollution spike", recommended_response: ["Deploy inspection team"], created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" };

  it("renders hotspot actual fields correctly", () => { render(<Hotspots hotspots={[sampleHotspot]} loading={false} error={null} selectedHotspotId="h-123" onSelectHotspot={() => {}} />); expect(screen.getByText("ID: h-123")).toBeInTheDocument(); expect(screen.getByText("Score: 86")).toBeInTheDocument(); expect(screen.getByText(/City: Bangalore/)).toBeInTheDocument(); });
  it("renders overview counts correctly", () => { const fed: FederationStatusResponse = { status: "ACTIVE", global_model_version: "v2.1", current_round: 14, registered_nodes: 8, healthy_nodes: 7, last_round: "2026-06-01", last_updated: "2026-06-01T12:00:00Z" }; render(<Overview hotspots={[sampleHotspot]} alerts={[baseAlert]} federation={fed} />); expect(screen.getByText("1")).toBeInTheDocument(); expect(screen.getByText("7/8")).toBeInTheDocument(); });
  it("renders map configuration-pending placeholder", () => { render(<MapPlaceholder />); expect(screen.getByText(/Geospatial map integration is pending configuration/)).toBeInTheDocument(); });
  it("tests alert state machine button rules correctly", () => { const statuses: Alert["status"][] = ["DETECTED","VALIDATING","HIGH_CONFIDENCE","ROUTED","ACKNOWLEDGED","ACTION_IN_PROGRESS","RESOLVED"]; statuses.forEach((status) => { const { unmount } = render(<Alerts alerts={[{ ...baseAlert, status }]} loading={false} error={null} onAlertAction={() => {}} />); if (status === "ROUTED") expect(screen.getByText("Acknowledge")).toBeInTheDocument(); else expect(screen.queryByText("Acknowledge")).not.toBeInTheDocument(); if (status === "ACKNOWLEDGED") expect(screen.getByText("Deploy Action")).toBeInTheDocument(); else expect(screen.queryByText("Deploy Action")).not.toBeInTheDocument(); if (status === "ACTION_IN_PROGRESS") expect(screen.getByText("Resolve")).toBeInTheDocument(); else expect(screen.queryByText("Resolve")).not.toBeInTheDocument(); unmount(); }); });
  it("calls updateAlertStatus for supported alert transitions", async () => { const cases: Array<[Alert["status"], string, string]> = [["ROUTED","Acknowledge","acknowledge"],["ACKNOWLEDGED","Deploy Action","action"],["ACTION_IN_PROGRESS","Resolve","resolve"]]; for (const [status,label,action] of cases) { (api.updateAlertStatus as jest.Mock).mockResolvedValue({ ...baseAlert, status: status }); render(<Alerts alerts={[{ ...baseAlert, event_id: `evt-${action}`, status }]} loading={false} error={null} onAlertAction={() => {}} />); fireEvent.click(screen.getByText(label)); await waitFor(() => expect(api.updateAlertStatus).toHaveBeenCalledWith(`evt-${action}`, action)); screen.unmount?.(); } });
  it("renders forecast, plume and exposure fields correctly", async () => { const forecast: ForecastResponse = { hotspot_id: "h-123", generated_at: "2026-01-01T00:00:00Z", model_name: "vayu-ml", forecasts: [{ horizon_minutes: 60, predicted_aqi: 220, confidence: 0.9 }] }; const plume: PlumeResponse = { hotspot_id: "h-123", generated_at: "2026-01-01T00:00:00Z", model: "dispersion-v1", horizons: [{ minutes: 60, center_latitude: 12.97, center_longitude: 77.59, radius_km: 3.5, intensity: 8, polygon: [{ lat: 12, lon: 77 }] }] }; const exposure: ExposureResponse = { estimated_population: 12500, area_km2: 15.2, confidence: 0.88, data_source: "census" }; (api.getForecast as jest.Mock).mockResolvedValue(forecast); (api.getPlume as jest.Mock).mockResolvedValue(plume); (api.getExposure as jest.Mock).mockResolvedValue(exposure); render(<Predictions hotspotId="h-123" />); await waitFor(() => { expect(screen.getByText("60 min")).toBeInTheDocument(); expect(screen.getByText(/AQI: 220/)).toBeInTheDocument(); expect(screen.getByText("3.5 km")).toBeInTheDocument(); expect(screen.getByText("12,500")).toBeInTheDocument(); }); });
  it("renders corridor prediction fields correctly", async () => { const corridor: CorridorPrediction[] = [{ corridor_name: "Ring Road Corridor", current_aqi: 180, predicted_aqi_1h: 195, predicted_aqi_2h: 210, predicted_aqi_3h: 200, predicted_peak_aqi: 220, time_to_peak_minutes: 120, risk_level: "HIGH", contributing_hotspot_id: "h-123", confidence: 0.9 }]; (api.getCorridorPredictions as jest.Mock).mockResolvedValue(corridor); render(<Corridors />); await waitFor(() => { expect(screen.getByText("Ring Road Corridor")).toBeInTheDocument(); expect(screen.getByText("HIGH")).toBeInTheDocument(); expect(screen.getByText(/Current AQI: 180/)).toBeInTheDocument(); }); });
  it("renders federation metrics correctly", () => { const fed: FederationStatusResponse = { status: "ACTIVE", global_model_version: "v2.1", current_round: 14, registered_nodes: 8, healthy_nodes: 7, last_round: "2026-06-01", last_updated: "2026-06-01T12:00:00Z" }; render(<Federation federation={fed} loading={false} error={null} />); expect(screen.getByText("v2.1")).toBeInTheDocument(); expect(screen.getByText("14")).toBeInTheDocument(); expect(screen.getByText("8")).toBeInTheDocument(); expect(screen.getByText("7")).toBeInTheDocument(); expect(screen.getByText("2026-06-01")).toBeInTheDocument(); });
  it("renders Gemini answer and tools_used correctly", async () => { const chat: AgentChatResponse = { answer: "AQI levels are elevated due to industrial emissions.", tools_used: ["query_hotspots"], grounding: [], data_sources: [], tool_selection_mode: "auto", language: "en" }; (api.chatWithAgent as jest.Mock).mockResolvedValue(chat); render(<GeminiPanel />); fireEvent.change(screen.getByPlaceholderText("Ask analyst..."), { target: { value: "Why is AQI high?" } }); fireEvent.keyDown(screen.getByPlaceholderText("Ask analyst..."), { key: "Enter", code: "Enter" }); await waitFor(() => { expect(screen.getByText(chat.answer)).toBeInTheDocument(); expect(screen.getByText(/Tools: query_hotspots/)).toBeInTheDocument(); }); });
});
